language: python

dist: xenial

matrix:
    include:
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.7"
          env: TOXENV=py37
        - python: "3.7"
          env: TOXENV=pep8
        - python: "3.7"
          env: TOXENV=fmt-check

install:
  pip install tox

script:
  tox

notifications:
  email: false
