# -*- coding: utf-8 -*-
#
# This file created with KivyCreatorProject
# <https://github.com/HeaTTheatR/KivyCreatorProgect
#
# Copyright (c) 2020 Ivanov Yuri and KivyMD
#
# For suggestions and questions:
# <kivydevelopment@gmail.com>
#
# LICENSE: MIT


<BaseScreen>:
    name: 'base'

    BoxLayout:
        orientation: 'vertical'

        Label:
            color: 0, 0, 0, 1
            font_size: '14sp'
            text:
                app.translation._('Замените этот экран на свой')